-- 1. 사원번호가 176 인 사원의 LAST_NAME, 부서번호 정보 조회
SELECT e.LAST_NAME , e.DEPARTMENT_ID FROM EMPLOYEES e WHERE e.EMPLOYEE_ID = 176;
-- 2. 급여 12000 이상 되는 직원들의 LAST_NAME, 급여 조회

SELECT e.LAST_NAME, e.SALARY FROM EMPLOYEES e WHERE e.SALARY >= 12000;
-- 3. 급여 5000 ~ 12000 범위가 아닌 사람들의 LAST_NAME, 급여 조회

SELECT e.LAST_NAME, e.SALARY FROM EMPLOYEES e WHERE e.SALARY < 5000 OR SALARY > 12000;

-- 4. 20번, 50번 부서에 근무하는 사원들의 LAST_NAME 오름차순, 부서번호 오름차순 조회
SELECT e.LAST_NAME, e.DEPARTMENT_ID FROM EMPLOYEES e WHERE e.DEPARTMENT_ID IN(20, 50) ORDER BY e.LAST_NAME ASC, DEPARTMENT_ID ASC;

-- 5. 커미션을 받는 모든 사원들의 LAST_NAME, 급여, 커미션을 조회, 급여 내림차순, 커미션 내림차순 조회
SELECT e.LAST_NAME, e.SALARY, e.COMMISSION_PCT FROM EMPLOYEES e WHERE e.COMMISSION_PCT > 0 ORDER BY e.SALARY DESC, e.COMMISSION_PCT DESC;

-- 6. 연봉이 2500, 3500, 7000이 아니며 직무가 SA_REP, ST_CLERK 인 사원 조회
SELECT * FROM EMPLOYEES e WHERE e.SALARY NOT IN(2500, 3500, 7000) AND e.JOB_ID IN('SA_REP', 'ST_CLERK'); 

-- 7. 2015/02/20 ~ 2015/05/01 사이에 고용된 사원들의 LAST_NAME, 사번, 고용일자(내림차순) 조회
SELECT e.LAST_NAME, e.EMPLOYEE_ID, e.HIRE_DATE FROM EMPLOYEES e WHERE e.HIRE_DATE >= '2015/02/20' AND e.HIRE_DATE <= '2015/05/01' ORDER BY e.HIRE_DATE DESC;

-- 8 ~ 10번 BETWEEN A AND B
--8. 20번, 50번 부서에서 근무하는 사원들 중에서 연봉이 5000 ~ 12000인 사원들의 LAST_NAME, 급여를 조회 후 급여의 오름차순 정렬
SELECT e.LAST_NAME , e.SALARY FROM EMPLOYEES e WHERE e.SALARY BETWEEN 5000 AND 12000;

--9.연봉이 5000 ~ 12000인 사원들의 LAST_NAME, 급여를 조회 후 급여의 오름차순 정렬
SELECT e.LAST_NAME, e.SALARY FROM EMPLOYEES e WHERE e.SALARY BETWEEN 5000 AND 12000 ORDER BY e.SALARY ASC;

-- 10. 2015/02/20 ~ 2015/05/01 사이에 고용된 사원들의 LAST_NAME, 사번, 고용일자(내림차순) 조회
SELECT e.LAST_NAME , e.EMPLOYEE_ID , e.HIRE_DATE FROM EMPLOYEES e WHERE e.HIRE_DATE BETWEEN '2015/02/20' AND '2015/05/01' ORDER BY e.HIRE_DATE DESC


-- LIKE
-- 11. LAST_NAME 에 u가 포함되는 사원들의 사번, LAST_NAME 조회
SELECT e.EMPLOYEE_ID ,e.LAST_NAME FROM EMPLOYEES e WHERE e.LAST_NAME LIKE '%u%';

-- 12. LAST_NAME 에 네 번째 글자가 a 인 사원들의 LAST_NAME 조회
SELECT e.LAST_NAME FROM EMPLOYEES e WHERE e.LAST_NAME LIKE '___a%';

-- 13. LAST_NAME 에 a 혹은 e 글자가 있는 사원들의 LAST_NAME 조회(LAST_NAME 오름차순)
SELECT e.LAST_NAME FROM EMPLOYEES e WHERE e.LAST_NAME LIKE '%a%' OR e.LAST_NAME LIKE '%e%' ORDER BY e.LAST_NAME ASC;

-- 14. LAST_NAME 에 a, e 글자가 포함된 사원들의 LAST_NAME 을 조회(LAST_NAME 오름차순)
SELECT e.LAST_NAME FROM EMPLOYEES e WHERE e.LAST_NAME LIKE '%a%' AND e.LAST_NAME LIKE '%e%' ORDER BY e.LAST_NAME DESC;
SELECT e.LAST_NAME FROM EMPLOYEES e WHERE e.LAST_NAME LIKE '%a%e%' OR e.LAST_NAME LIKE '%e%a%' ORDER BY e.LAST_NAME DESC;

-- is null / is not null
-- 15. 매니저 아이디가 없는 사원들의 LAST_NAME을 조회(LAST_NAME, JOB_ID 조회)
SELECT e.LAST_NAME, e.JOB_ID FROM EMPLOYEES e WHERE e.MANAGER_ID IS NULL;

-- 16. 직무가 ST_CLERK인 사원이 근무하고 있지 않은 부서 id 조회
-- 단, 부서번호가 null인 것은 제외, 중복제거(DISTINCT)
SELECT DISTINCT e.DEPARTMENT_ID FROM EMPLOYEES e WHERE e.JOB_ID !='ST_CLERK' AND e.DEPARTMENT_ID IS NOT null;

-- 17. COMMISSION_PCT 가 NULL 이 아닌 사원들 중에서 COMMISSION = SALARY * COMMISSION_PCT
-- 를 구하여 사번, FIRST_NAME, JOB_ID 조회
SELECT e.EMPLOYEE_ID ,e.FIRST_NAME ,e.JOB_ID, e.SALARY * COMMISSION_PCT AS COMMISSION FROM EMPLOYEES e WHERE e.COMMISSION_PCT IS NOT NULL;
















